# Generated by Django 5.0.6 on 2024-07-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
