# Generated by Django 5.0.6 on 2024-07-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
