# Generated by Django 5.0.6 on 2024-07-02 22:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nosotros', verbose_name='Imagen')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('trayectoria', ckeditor.fields.RichTextField(verbose_name='Trayectoria')),
            ],
            options={
                'verbose_name': 'nosotros',
                'ordering': ['-name'],
            },
        ),
    ]
