# Generated by Django 5.0.6 on 2024-07-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosotros',
            options={'ordering': ['-name'], 'verbose_name': 'nosotros', 'verbose_name_plural': 'Nosotros'},
        ),
        migrations.AddField(
            model_name='nosotros',
            name='puesto',
            field=models.CharField(default='default puesto', max_length=100, verbose_name='Especialidad'),
            preserve_default=False,
        ),
    ]
